# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: materialprop
    build: .
    command: gunicorn -b 0.0.0.0:5000 materialprop.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/materialprop.db
    volumes:
      - ./materialprop:/code/materialprop
      - ./db/:/db/
    ports:
      - "5000:5000"
